---
extends: default
rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  document-start:
    present: true
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

