---
# yamllint disable-line rule:document-start
# Azure Devops Pipeline
# UAT Deployment Pipeline

trigger:
  branches:
    include:
      - main

pr: none

variables:
  phpVersion: '8.4'
  imageRepository: 'newlabbackened'
  containerRegistry: 'tedlance.azurecr.io'
  tag: 'uat'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          vmImage: $(vmImageName)
        steps:
          - checkout: self
          - script: |
              sudo add-apt-repository ppa:ondrej/php -y
              sudo apt-get update
              sudo apt-get install -y php8.4-cli php8.4-xml php8.4-curl php8.4-mbstring

            displayName: "Install PHP 8.4"
          - script: |
              sudo update-alternatives --set php /usr/bin/php$(phpVersion)
              php -version
            displayName: "Set PHP version $(phpVersion)"
          - script: composer install --no interaction --prefer-dist
            displayName: "Composer Install"
